[profile.default]
src = 'contracts/fundme-contracts/contracts'
out = "out"
libs = ["lib"]

remappings = [
    "openzeppelin/=lib/openzeppelin-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
